/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        darkGray: "#333333",
        mediumGrey: "#737373",
        borderColor: "#D9D9D9",
        primary: "#633CFF",
        lightPurple: "#EFEBFF",
        siteBg: "#FAFAFA",
        lightGray: "#FAFAFA",
        error: "#FF3939",
        github: "#1c2022",
        google: "#4285F4",
        linkedin: "#0A66C2",
        discord: "#5865F2",
        githubLinkText: "#FFFFFF",
        githubLinkBg: "#1A1A1A",
        frontendMentorLinkText: "#000000",
        frontendMentorLinkBg: "#FFFFFF",
        twitterLinkText: "#FFFFFF",
        twitterLinkBg: "#43B7E9",
        youtubeLinkText: "#FFFFFF",
        youtubeLinkBg: "#EE3939",
        facebookLinkText: "#FFFFFF",
        facebookLinkBg: "#2442AC",
        twitchLinkText: "#FFFFFF",
        twitchLinkBg: "#EE3FC8",
        devToLinkText: "#FFFFFF",
        devToLinkBg: "#333333",
        codewarsLinkText: "#FFFFFF",
        codewarsLinkBg: "#8A1A50",
        freeCodeCampLinkText: "#FFFFFF",
        freeCodeCampLinkBg: "#302267",
        gitLabLinkText: "#FFFFFF",
        gitLabLinkBg: "#EB4925",
        hashNodeLinkText: "#FFFFFF",
        hashNodeLinkBg: "#0330D1",
        stackOverflowLinkText: "#FFFFFF",
        stackOverflowLinkBg: "#EC7100",
      },
      boxShadow: {
        inputFocus: "0px 0px 32px 0px rgba(99, 60, 255, 0.25)",
      },
      fontFamily: {
        Instrument: "Instrument",
      },
    },
  },
  plugins: [],
};
