export const config = {
  PORT: process.env.PORT || 5000,
  NODE_ENV: process.env.NODE_ENV! as "development" | "production",
  CLIENT_BASE_URL: process.env.CLIENT_BASE_URL!,
  DB_HOST: process.env.DB_HOST!,
  DB_PORT: Number(process.env.DB_PORT!),
  DB_USER: process.env.DB_USER!,
  DB_PASS: process.env.DB_PASS!,
  DB_NAME: process.env.DB_NAME!,
  PASSWORD_SALT_ROUNDS: Number(process.env.PASSWORD_SALT_ROUNDS!),
  SECURE_PASSWORD_GENERATOR_LENGTH: Number(process.env.SECURE_PASSWORD_GENERATOR_LENGTH!),
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID!,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET!,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID!,
  LINKEDIN_CLIENT_SECRET: process.env.LINKEDIN_CLIENT_SECRET!,
  DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID!,
  DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET!,
  secrets: {
    ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET!,
    REFRESH_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET!,
  },
};
